server:
  port: ${PORT:8080}

spring:
  application:
    name: pivnitsa-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pivnitsa}
    username: ${DB_USERNAME:pivnitsa}
    password: ${DB_PASSWORD:pivnitsa}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized
