CREATE TABLE staff (
    id  BIGSERIAL   PRIMARY KEY,
    full_name   VARCHAR(255) NOT NULL,
    email   VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    role    VARCHAR(255) NOT NULL DEFAULT 'STAFF',
    can_view_financial_report   BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);